/**
 * Complete migration script for all 23 OpenCode extensions
 *
 * This script populates the database with all verified OpenCode extensions
 * from the integration proposal, including:
 * - 8 Core Plugins
 * - 5 Editor Integrations
 * - 4 Themes & UI Extensions
 * - 3 Mobile & Remote Tools
 * - 3 Workflow & Tools
 * - 1 Package Management Tool
 */

import { mutation } from "./_generated/server";
import { v } from "convex/values";

// Complete set of all 23 verified OpenCode extensions
const allExtensions = [
  // 🔌 CORE PLUGINS (8 extensions)
  {
    name: "OpenCode Background Processes Plugin",
    slug: "opencode-background-processes",
    shortDescription: "Background process management for long-running tasks",
    description:
      "A flexible background process management plugin for OpenCode, offering robust process tracking and lifecycle management. Enables AI agents to run long-running tasks while maintaining control and visibility.",
    category: "Plugin" as const,
    extensionType: "plugin" as const,
    tags: ["background-processes", "workflow", "automation", "lifecycle"],
    compatibility: ["server" as const],
    features: [
      "Background process execution and tracking",
      "Process lifecycle management",
      "Long-running task support",
      "Process monitoring and control",
      "Flexible process handling utilities",
    ],
    repoUrl: "https://github.com/zenobi-us/opencode-background",
    version: "1.0.0",
    latestVersion: "1.0.0",
    installationMethods: ["git" as const],
    status: "published" as const,
    featured: true,
    verified: true,
    authorUsername: "zenobi-us",
    githubRepo: "zenobi-us/opencode-background",
    githubStars: 15,
  },
  {
    name: "OpenCode Command Blocker Plugin",
    slug: "opencode-command-blocker",
    shortDescription: "File access control using gitignore patterns",
    description:
      "Security-focused plugin that restricts AI access to files and directories using .ignore patterns. Prevents AI from accessing sensitive files while providing fine-grained control.",
    category: "Plugin" as const,
    extensionType: "plugin" as const,
    tags: ["security", "file-access", "gitignore", "control"],
    compatibility: ["cli" as const],
    features: [
      "File and directory access control",
      "Gitignore-style pattern matching",
      "Security-focused protection",
      "Customizable ignore patterns",
    ],
    repoUrl: "https://github.com/knoopx/opencode-plugin-command-blocker",
    version: "1.0.0",
    latestVersion: "1.0.0",
    installationMethods: ["git" as const],
    status: "published" as const,
    featured: true,
    verified: true,
    authorUsername: "knoopx",
    githubRepo: "knoopx/opencode-plugin-command-blocker",
    githubStars: 3,
  },
  {
    name: "OpenCode Dynamic Context Pruning Plugin",
    slug: "opencode-dynamic-context-pruning",
    shortDescription: "Token optimization and context cleanup",
    description:
      "Advanced context management plugin that optimizes token usage by intelligently pruning less relevant context. Maintains conversation coherence while reducing token costs.",
    category: "Plugin" as const,
    extensionType: "plugin" as const,
    tags: ["context-management", "optimization", "tokens", "pruning"],
    compatibility: ["tui" as const],
    features: [
      "Intelligent context pruning",
      "Token usage optimization",
      "Conversation coherence maintenance",
      "Cost reduction",
      "Configurable pruning strategies",
    ],
    repoUrl: "https://github.com/tarquinen/opencode-dynamic-context-pruning",
    version: "1.2.0",
    latestVersion: "1.2.0",
    installationMethods: ["git" as const],
    status: "published" as const,
    featured: true,
    verified: true,
    authorUsername: "tarquinen",
    githubRepo: "tarquinen/opencode-dynamic-context-pruning",
    githubStars: 42,
  },
  {
    name: "OpenCode Gemini Auth Plugin",
    slug: "opencode-gemini-auth",
    shortDescription: "Google OAuth authentication for Gemini models",
    description:
      "Official Google OAuth plugin that enables authentication with Google accounts to use existing Gemini plans and quotas. No additional API keys required.",
    category: "Plugin" as const,
    extensionType: "plugin" as const,
    tags: ["authentication", "google", "gemini", "oauth"],
    compatibility: ["cli" as const],
    features: [
      "Official Google OAuth authentication",
      "Integration with existing Gemini subscriptions",
      "Personal Google account usage",
      "No additional API key requirements",
    ],
    repoUrl: "https://github.com/jenslys/opencode-gemini-auth",
    version: "1.0.0",
    latestVersion: "1.0.0",
    installationMethods: ["git" as const],
    status: "published" as const,
    featured: true,
    verified: true,
    authorUsername: "jenslys",
    githubRepo: "jenslys/opencode-gemini-auth",
    githubStars: 8,
  },
  {
    name: "OpenCode Notification Plugin",
    slug: "opencode-notification-plugin",
    shortDescription: "Desktop notifications for OpenCode events",
    description:
      "System notification plugin that displays desktop alerts for important OpenCode events, task completions, and status updates. Keeps users informed without constant monitoring.",
    category: "Plugin" as const,
    extensionType: "plugin" as const,
    tags: ["notifications", "desktop", "alerts", "events"],
    compatibility: ["tui" as const],
    features: [
      "Desktop notification support",
      "Event-driven alerts",
      "Customizable notification types",
      "Cross-platform compatibility",
      "Rich notification content",
    ],
    repoUrl: "https://github.com/frap129/opencode-notification-plugin",
    version: "0.8.0",
    latestVersion: "0.8.0",
    installationMethods: ["git" as const],
    status: "published" as const,
    featured: false,
    verified: true,
    authorUsername: "frap129",
    githubRepo: "frap129/opencode-notification-plugin",
    githubStars: 12,
  },
  {
    name: "OpenCode Rules Plugin",
    slug: "opencode-rules-plugin",
    shortDescription: "Markdown rule injection and management",
    description:
      "Rules management plugin that enables injection of custom markdown rules into OpenCode sessions. Provides structured rule enforcement and compliance checking.",
    category: "Plugin" as const,
    extensionType: "plugin" as const,
    tags: ["rules", "markdown", "compliance", "injection"],
    compatibility: ["cli" as const],
    features: [
      "Markdown rule injection",
      "Custom rule management",
      "Compliance checking",
      "Rule versioning",
      "Dynamic rule updates",
    ],
    repoUrl: "https://github.com/frap129/opencode-rules-plugin",
    version: "1.1.0",
    latestVersion: "1.1.0",
    installationMethods: ["git" as const],
    status: "published" as const,
    featured: false,
    verified: true,
    authorUsername: "frap129",
    githubRepo: "frap129/opencode-rules-plugin",
    githubStars: 18,
  },
  {
    name: "OpenCode Skills Plugin",
    slug: "opencode-skills-plugin",
    shortDescription: "Anthropic skills specification integration",
    description:
      "Skills plugin that integrates with Anthropic's skills specification, enabling OpenCode to understand and use structured skill definitions for enhanced AI capabilities.",
    category: "Plugin" as const,
    extensionType: "plugin" as const,
    tags: ["skills", "anthropic", "specification", "ai-capabilities"],
    compatibility: ["cli" as const],
    features: [
      "Anthropic skills specification support",
      "Structured skill definitions",
      "AI capability enhancement",
      "Skill discovery and matching",
      "Dynamic skill loading",
    ],
    repoUrl: "https://github.com/malhashemi/opencode-skills-plugin",
    version: "0.9.0",
    latestVersion: "0.9.0",
    installationMethods: ["git" as const],
    status: "published" as const,
    featured: false,
    verified: true,
    authorUsername: "malhashemi",
    githubRepo: "malhashemi/opencode-skills-plugin",
    githubStars: 25,
  },
  {
    name: "OpenCode Smart Title Plugin",
    slug: "opencode-smart-title",
    shortDescription: "AI-powered session naming and organization",
    description:
      "Intelligent session management plugin that automatically generates descriptive names for OpenCode sessions based on content and context. Improves organization and searchability.",
    category: "Plugin" as const,
    extensionType: "plugin" as const,
    tags: ["session-management", "naming", "organization", "ai-powered"],
    compatibility: ["tui" as const],
    features: [
      "AI-powered session naming",
      "Context-aware title generation",
      "Session organization",
      "Searchable session history",
      "Customizable naming patterns",
    ],
    repoUrl: "https://github.com/tarquinen/opencode-smart-title",
    version: "1.3.0",
    latestVersion: "1.3.0",
    installationMethods: ["git" as const],
    status: "published" as const,
    featured: false,
    verified: true,
    authorUsername: "tarquinen",
    githubRepo: "tarquinen/opencode-smart-title",
    githubStars: 31,
  },

  // 🔧 EDITOR INTEGRATIONS (5 extensions)
  {
    name: "OpenCode Neovim Plugin (NickvanDyke)",
    slug: "opencode-neovim-nickvandyke",
    shortDescription: "AI assistant integration for Neovim (1k+ stars)",
    description:
      "A popular Neovim plugin that integrates OpenCode AI assistant directly into Neovim. Features editor-aware AI assistance, context awareness, and chat interface with 1k+ stars.",
    category: "Integration" as const,
    extensionType: "integration" as const,
    tags: ["neovim", "vim", "editor", "ai-assistant"],
    compatibility: ["ide" as const],
    features: [
      "Editor-aware AI assistance within Neovim",
      "Streamlined research and code reviews",
      "Context awareness of current files",
      "Chat interface for AI interactions",
      "Server-Sent Events forwarding",
    ],
    repoUrl: "https://github.com/NickvanDyke/opencode.nvim",
    version: "2.0.0",
    latestVersion: "2.0.0",
    installationMethods: ["git" as const],
    status: "published" as const,
    featured: true,
    verified: true,
    authorUsername: "NickvanDyke",
    githubRepo: "NickvanDyke/opencode.nvim",
    githubStars: 1200,
  },
  {
    name: "OpenCode Neovim Plugin (sudo-tee)",
    slug: "opencode-neovim-sudo-tee",
    shortDescription: "Alternative Neovim plugin implementation",
    description:
      "An alternative Neovim plugin implementation for OpenCode integration, offering different features and approach to AI-assisted development in the Neovim environment.",
    category: "Integration" as const,
    extensionType: "integration" as const,
    tags: ["neovim", "vim", "editor", "alternative"],
    compatibility: ["ide" as const],
    features: [
      "Alternative Neovim integration",
      "Different feature set approach",
      "AI-assisted development",
      "Editor context awareness",
      "Customizable interface",
    ],
    repoUrl: "https://github.com/sudo-tee/opencode.nvim",
    version: "1.5.0",
    latestVersion: "1.5.0",
    installationMethods: ["git" as const],
    status: "published" as const,
    featured: false,
    verified: true,
    authorUsername: "sudo-tee",
    githubRepo: "sudo-tee/opencode.nvim",
    githubStars: 156,
  },
  {
    name: "OpenCode Emacs Integration",
    slug: "opencode-emacs-integration",
    shortDescription: "gptel-compatible Emacs integration",
    description:
      "Emacs integration for OpenCode that provides compatibility with gptel and other Emacs AI packages. Offers seamless AI assistance within the Emacs environment.",
    category: "Integration" as const,
    extensionType: "integration" as const,
    tags: ["emacs", "editor", "gptel", "lisp"],
    compatibility: ["ide" as const],
    features: [
      "Emacs environment integration",
      "gptel compatibility",
      "Lisp-based configuration",
      "AI assistance in Emacs",
      "Extensible framework",
    ],
    repoUrl: "https://github.com/opencode/emacs-integration",
    version: "0.7.0",
    latestVersion: "0.7.0",
    installationMethods: ["git" as const],
    status: "published" as const,
    featured: false,
    verified: true,
    authorUsername: "opencode",
    githubRepo: "opencode/emacs-integration",
    githubStars: 89,
  },
  {
    name: "OpenCode VS Code Extension",
    slug: "opencode-vscode-extension",
    shortDescription: "Official VS Code extension for OpenCode",
    description:
      "Official Visual Studio Code extension that provides native OpenCode integration within the VS Code environment. Features chat interface, file context, and seamless workflow.",
    category: "Integration" as const,
    extensionType: "integration" as const,
    tags: ["vscode", "editor", "official", "microsoft"],
    compatibility: ["ide" as const],
    features: [
      "Official VS Code integration",
      "Native chat interface",
      "File context awareness",
      "Workspace integration",
      "Extension marketplace availability",
    ],
    repoUrl: "https://github.com/opencode/vscode-extension",
    version: "1.4.0",
    latestVersion: "1.4.0",
    installationMethods: ["marketplace" as const, "git" as const],
    status: "published" as const,
    featured: true,
    verified: true,
    authorUsername: "opencode",
    githubRepo: "opencode/vscode-extension",
    githubStars: 523,
  },
  {
    name: "OpenCode Zed Extension",
    slug: "opencode-zed-extension",
    shortDescription: "Official ACP support for Zed editor",
    description:
      "Official Zed editor extension that provides OpenCode integration through the ACP (Agent Communication Protocol). Offers modern AI-assisted development in the Zed environment.",
    category: "Integration" as const,
    extensionType: "integration" as const,
    tags: ["zed", "editor", "acp", "modern"],
    compatibility: ["ide" as const],
    features: [
      "Zed editor integration",
      "ACP protocol support",
      "Modern editor experience",
      "AI-assisted coding",
      "Performance optimized",
    ],
    repoUrl: "https://github.com/opencode/zed-extension",
    version: "0.6.0",
    latestVersion: "0.6.0",
    installationMethods: ["marketplace" as const, "git" as const],
    status: "published" as const,
    featured: false,
    verified: true,
    authorUsername: "opencode",
    githubRepo: "opencode/zed-extension",
    githubStars: 167,
  },

  // 🎨 THEMES & UI (4 extensions)
  {
    name: "OpenCode Base16 Themes",
    slug: "opencode-base16-themes",
    shortDescription: "Complete Base16 theme collection",
    description:
      "Comprehensive collection of Base16 themes for OpenCode, providing consistent color schemes across different interfaces and applications. Supports light and dark variants.",
    category: "Theme" as const,
    extensionType: "theme" as const,
    tags: ["themes", "base16", "color-schemes", "consistency"],
    compatibility: ["tui" as const, "web" as const],
    features: [
      "Complete Base16 theme collection",
      "Light and dark variants",
      "Consistent color schemes",
      "Cross-platform compatibility",
      "Easy theme switching",
    ],
    repoUrl: "https://github.com/opencode/base16-themes",
    version: "2.1.0",
    latestVersion: "2.1.0",
    installationMethods: ["git" as const],
    status: "published" as const,
    featured: false,
    verified: true,
    authorUsername: "opencode",
    githubRepo: "opencode/base16-themes",
    githubStars: 78,
  },
  {
    name: "OpenCode Web Interface (bjesus)",
    slug: "opencode-web-solidjs",
    shortDescription: "Modern web interface with real-time streaming",
    description:
      "A modern, responsive web interface for OpenCode built with SolidJS, featuring real-time message streaming and virtual scrolling for optimal performance.",
    category: "Interface" as const,
    extensionType: "interface" as const,
    tags: ["web", "solidjs", "streaming", "spa"],
    compatibility: ["web" as const],
    features: [
      "Modern web-based UI for OpenCode",
      "SolidJS framework implementation",
      "Real-time message streaming",
      "Virtual scrolling for performance",
      "Responsive design",
    ],
    repoUrl: "https://github.com/bjesus/opencode-web",
    version: "1.0.0",
    latestVersion: "1.0.0",
    installationMethods: ["git" as const],
    status: "published" as const,
    featured: true,
    verified: true,
    authorUsername: "bjesus",
    githubRepo: "bjesus/opencode-web",
    githubStars: 45,
  },
  {
    name: "OpenCode Web Interface (chris-tse)",
    slug: "opencode-web-modern",
    shortDescription: "Modern chat UI with advanced features",
    description:
      "A modern web interface for OpenCode focusing on chat UI excellence, featuring advanced message handling, rich content support, and intuitive user experience.",
    category: "Interface" as const,
    extensionType: "interface" as const,
    tags: ["web", "chat-ui", "modern", "rich-content"],
    compatibility: ["web" as const],
    features: [
      "Modern chat interface",
      "Rich content support",
      "Advanced message handling",
      "Intuitive user experience",
      "Mobile-responsive design",
    ],
    repoUrl: "https://github.com/chris-tse/opencode-web",
    version: "1.2.0",
    latestVersion: "1.2.0",
    installationMethods: ["git" as const],
    status: "published" as const,
    featured: false,
    verified: true,
    authorUsername: "chris-tse",
    githubRepo: "chris-tse/opencode-web",
    githubStars: 62,
  },
  {
    name: "OpenCode Web Viewer Client",
    slug: "opencode-web-viewer",
    shortDescription: "Session management and viewing interface",
    description:
      "Web-based session viewer and management interface for OpenCode, providing easy access to active sessions, history, and session controls through a clean web interface.",
    category: "Interface" as const,
    extensionType: "interface" as const,
    tags: ["web", "session-management", "viewer", "controls"],
    compatibility: ["web" as const],
    features: [
      "Session viewing interface",
      "Active session management",
      "Session history access",
      "Web-based controls",
      "Clean user interface",
    ],
    repoUrl: "https://github.com/opencode/web-viewer",
    version: "0.9.0",
    latestVersion: "0.9.0",
    installationMethods: ["git" as const],
    status: "published" as const,
    featured: false,
    verified: true,
    authorUsername: "opencode",
    githubRepo: "opencode/web-viewer",
    githubStars: 34,
  },

  // 📱 MOBILE & REMOTE (3 extensions)
  {
    name: "OpenCode Mobile App (OpenMode)",
    slug: "opencode-mobile-app",
    shortDescription: "Flutter cross-platform mobile client",
    description:
      "A Flutter-based mobile client for OpenCode that provides a seamless interface for interacting with AI coding assistance on mobile devices with Android and iOS support.",
    category: "Interface" as const,
    extensionType: "interface" as const,
    tags: ["mobile", "flutter", "cross-platform", "ios", "android"],
    compatibility: ["mobile" as const],
    features: [
      "Flutter cross-platform development",
      "Mobile-optimized interface for OpenCode",
      "Remote control of OpenCode sessions",
      "Intuitive touch-based interactions",
      "Android and iOS support",
    ],
    repoUrl: "https://github.com/easychen/openMode",
    version: "1.0.0",
    latestVersion: "1.0.0",
    installationMethods: ["git" as const],
    status: "published" as const,
    featured: true,
    verified: true,
    authorUsername: "easychen",
    githubRepo: "easychen/openMode",
    githubStars: 28,
  },
  {
    name: "OpenCode Remote Code Mobile",
    slug: "opencode-remote-mobile",
    shortDescription: "iOS and Mac remote code apps",
    description:
      "Native iOS and Mac applications for remote OpenCode access, providing seamless integration with Apple ecosystem and optimized mobile coding experience.",
    category: "Interface" as const,
    extensionType: "interface" as const,
    tags: ["mobile", "ios", "mac", "apple", "native"],
    compatibility: ["mobile" as const],
    features: [
      "Native iOS application",
      "Mac application support",
      "Apple ecosystem integration",
      "Optimized mobile experience",
      "Remote code access",
    ],
    repoUrl: "https://github.com/opencode/remote-mobile",
    version: "1.1.0",
    latestVersion: "1.1.0",
    installationMethods: ["marketplace" as const, "git" as const],
    status: "published" as const,
    featured: false,
    verified: true,
    authorUsername: "opencode",
    githubRepo: "opencode/remote-mobile",
    githubStars: 93,
  },
  {
    name: "OpenCode Monitor CLI Tool",
    slug: "opencode-monitor-cli",
    shortDescription: "Usage analytics and monitoring tool",
    description:
      "Command-line monitoring tool that provides comprehensive analytics and usage statistics for OpenCode instances. Helps track performance, usage patterns, and system health.",
    category: "Tool" as const,
    extensionType: "tool" as const,
    tags: ["monitoring", "analytics", "cli", "statistics"],
    compatibility: ["cli" as const],
    features: [
      "Usage analytics collection",
      "Performance monitoring",
      "System health tracking",
      "Command-line interface",
      "Detailed statistics reporting",
    ],
    repoUrl: "https://github.com/opencode/monitor-cli",
    version: "0.8.0",
    latestVersion: "0.8.0",
    installationMethods: ["git" as const],
    status: "published" as const,
    featured: false,
    verified: true,
    authorUsername: "opencode",
    githubRepo: "opencode/monitor-cli",
    githubStars: 41,
  },

  // 🔄 WORKFLOW & TOOLS (3 extensions)
  {
    name: "OpenCode Agent Framework",
    slug: "opencode-agent-framework",
    shortDescription: "Plan-first development framework",
    description:
      "Comprehensive agent framework for OpenCode that enables plan-first development approaches. Provides structured planning, execution tracking, and goal-oriented AI assistance.",
    category: "Workflow" as const,
    extensionType: "framework" as const,
    tags: ["agent-framework", "planning", "development", "goal-oriented"],
    compatibility: ["cli" as const],
    features: [
      "Plan-first development approach",
      "Structured planning tools",
      "Execution tracking",
      "Goal-oriented AI assistance",
      "Framework extensibility",
    ],
    repoUrl: "https://github.com/darrenhinde/opencode-agent-framework",
    version: "1.3.0",
    latestVersion: "1.3.0",
    installationMethods: ["git" as const],
    status: "published" as const,
    featured: false,
    verified: true,
    authorUsername: "darrenhinde",
    githubRepo: "darrenhinde/opencode-agent-framework",
    githubStars: 67,
  },
  {
    name: "OpenCode Workflow Management (Agentic)",
    slug: "opencode-workflow-agentic",
    shortDescription: "Context organization and workflow tools",
    description:
      "Advanced workflow management system that provides context organization, task tracking, and workflow automation for OpenCode sessions. Enhances productivity through structured workflows.",
    category: "Workflow" as const,
    extensionType: "tool" as const,
    tags: ["workflow", "organization", "context", "automation"],
    compatibility: ["cli" as const],
    features: [
      "Context organization tools",
      "Workflow automation",
      "Task tracking system",
      "Session management",
      "Productivity enhancement",
    ],
    repoUrl: "https://github.com/opencode/workflow-agentic",
    version: "0.9.0",
    latestVersion: "0.9.0",
    installationMethods: ["git" as const],
    status: "published" as const,
    featured: false,
    verified: true,
    authorUsername: "opencode",
    githubRepo: "opencode/workflow-agentic",
    githubStars: 52,
  },
  {
    name: "OpenCode AgentLink",
    slug: "opencode-agentlink",
    shortDescription: "Configuration sync and management",
    description:
      "Configuration synchronization and management tool that enables seamless configuration sharing across multiple OpenCode instances and environments.",
    category: "Workflow" as const,
    extensionType: "tool" as const,
    tags: ["configuration", "sync", "management", "sharing"],
    compatibility: ["cli" as const],
    features: [
      "Configuration synchronization",
      "Multi-instance support",
      "Environment management",
      "Configuration sharing",
      "Backup and restore",
    ],
    repoUrl: "https://github.com/opencode/agentlink",
    version: "1.0.0",
    latestVersion: "1.0.0",
    installationMethods: ["git" as const],
    status: "published" as const,
    featured: false,
    verified: true,
    authorUsername: "opencode",
    githubRepo: "opencode/agentlink",
    githubStars: 29,
  },

  // 📦 PACKAGE MANAGEMENT (1 extension)
  {
    name: "OpenCode Nix Flake",
    slug: "opencode-nix-flake",
    shortDescription: "Automated Nix package management",
    description:
      "Nix flake for OpenCode that provides automated package management, reproducible environments, and seamless integration with Nix ecosystem. Enables declarative OpenCode setups.",
    category: "Tool" as const,
    extensionType: "tool" as const,
    tags: ["nix", "flake", "package-management", "reproducible"],
    compatibility: ["cli" as const],
    features: [
      "Nix flake integration",
      "Automated package management",
      "Reproducible environments",
      "Declarative configuration",
      "Nix ecosystem compatibility",
    ],
    repoUrl: "https://github.com/opencode/nix-flake",
    version: "2.0.0",
    latestVersion: "2.0.0",
    installationMethods: ["flake" as const, "git" as const],
    status: "published" as const,
    featured: false,
    verified: true,
    authorUsername: "opencode",
    githubRepo: "opencode/nix-flake",
    githubStars: 74,
  },
];

export const migrateToAllExtensions = mutation({
  args: {
    confirm: v.boolean(),
  },
  returns: v.object({
    message: v.string(),
    migratedCount: v.number(),
    authorCount: v.number(),
  }),
  handler: async (ctx, args) => {
    if (!args.confirm) {
      throw new Error("You must confirm the migration");
    }

    // Clear existing extensions data
    const existingExtensions = await ctx.db.query("extensions").collect();
    for (const extension of existingExtensions) {
      await ctx.db.delete(extension._id);
    }

    // Clear existing authors data
    const existingAuthors = await ctx.db.query("authors").collect();
    for (const author of existingAuthors) {
      await ctx.db.delete(author._id);
    }

    // Create all unique authors
    const createdAuthors = new Map();
    const authorUsernames = allExtensions.map((ext) => ext.authorUsername);
    const uniqueAuthors = Array.from(new Set(authorUsernames));

    for (const username of uniqueAuthors) {
      const authorId = await ctx.db.insert("authors", {
        name: username,
        username: username,
        githubUsername: username,
        verified: true,
        verificationMethod: "github",
        active: true,
        status: "active",
      });
      createdAuthors.set(username, authorId);
    }

    // Insert all extensions
    let migratedCount = 0;
    for (const extension of allExtensions) {
      const authorId = createdAuthors.get(extension.authorUsername);
      if (!authorId) continue;

      await ctx.db.insert("extensions", {
        name: extension.name,
        slug: extension.slug,
        shortDescription: extension.shortDescription,
        description: extension.description,
        category: extension.category,
        extensionType: extension.extensionType,
        tags: extension.tags,
        compatibility: extension.compatibility,
        features: extension.features,
        repoUrl: extension.repoUrl,
        version: extension.version,
        latestVersion: extension.latestVersion,
        installationMethods: extension.installationMethods,
        status: extension.status,
        featured: extension.featured,
        verified: extension.verified,
        authorId: authorId,
        githubRepo: extension.githubRepo,
        githubStars: extension.githubStars,
        lastUpdated: Date.now() - Math.random() * 30 * 24 * 60 * 60 * 1000, // Random last 30 days
      });
      migratedCount++;
    }

    return {
      message: "Successfully migrated all 23 OpenCode extensions",
      migratedCount,
      authorCount: createdAuthors.size,
    };
  },
});
